// Fixed reference rankings for new-grad software engineering opportunities.
// Edit ranks here; the Jobs UI sorts by these values automatically.
const TECH_RANKING_VERSION = '2026-09-17';

// Locations that belong to a ranked city rather than its surrounding metro.
const TECH_CITY_APPLICATION_ALIASES = {
  'New York City':['New York','Manhattan','Brooklyn','Queens','Bronx','The Bronx','Staten Island'],
};

const techMetros = [
  { id:'nyc', name:'NYC Metro', metroTechRank:1, includedAreas:['New York City','Jersey City','Newark','Brooklyn','Queens'] },
  { id:'san-francisco', name:'San Francisco Metro', metroTechRank:2, includedAreas:['San Francisco','Oakland','Redwood City'] },
  { id:'san-jose', name:'San Jose Metro', metroTechRank:3, includedAreas:['San Jose','Palo Alto','Mountain View','Sunnyvale','Santa Clara'] },
  { id:'seattle', name:'Seattle Metro', metroTechRank:4, includedAreas:['Seattle','Bellevue','Redmond','Kirkland'] },
  { id:'austin', name:'Austin Metro', metroTechRank:5, includedAreas:['Austin','Round Rock','Cedar Park'] },
  { id:'dc-nova', name:'DC / Northern Virginia', metroTechRank:6, includedAreas:['Washington, DC','Arlington','Alexandria','Tysons','McLean','Reston','Herndon','Bethesda'] },
  { id:'dallas-fort-worth', name:'Dallas–Fort Worth', metroTechRank:7, includedAreas:['Dallas','Fort Worth','Plano','Frisco','Irving','Richardson'] },
  { id:'boston', name:'Boston Metro', metroTechRank:8, includedAreas:['Boston','Cambridge','Somerville','Waltham'] },
  { id:'los-angeles', name:'Los Angeles Metro', metroTechRank:9, includedAreas:['Los Angeles','Long Beach','Santa Monica','Culver City','El Segundo'] },
  { id:'orange-county', name:'Orange County Metro', metroTechRank:10, includedAreas:['Irvine','Costa Mesa','Newport Beach'] },
  { id:'chicago', name:'Chicago Metro', metroTechRank:11, includedAreas:['Chicago','Evanston','Naperville'] },
  { id:'raleigh-durham', name:'Raleigh–Durham / Research Triangle', metroTechRank:12, includedAreas:['Raleigh','Durham','Research Triangle Park','Chapel Hill','Cary'] },
  { id:'philadelphia', name:'Philadelphia Metro', metroTechRank:13, includedAreas:['Philadelphia','King of Prussia','Conshohocken'] },
  { id:'san-diego', name:'San Diego Metro', metroTechRank:14, includedAreas:['San Diego','La Jolla','Carlsbad'] },
  { id:'denver-boulder', name:'Denver / Boulder', metroTechRank:15, includedAreas:['Denver','Boulder','Broomfield','Englewood'] },
  { id:'phoenix', name:'Phoenix Metro', metroTechRank:16, includedAreas:['Phoenix','Tempe','Scottsdale','Chandler'] },
  { id:'salt-lake-city', name:'Salt Lake City / Wasatch Front', metroTechRank:17, includedAreas:['Salt Lake City','Lehi','Provo','Draper'] },
  { id:'baltimore', name:'Baltimore–Columbia', metroTechRank:18, includedAreas:['Baltimore','Columbia','Ellicott City'] },
  { id:'charlotte', name:'Charlotte Metro', metroTechRank:19 },
  { id:'nashville', name:'Nashville Metro', metroTechRank:20 },
  { id:'pittsburgh', name:'Pittsburgh Metro', metroTechRank:21 },
  { id:'south-florida', name:'South Florida / Miami', metroTechRank:22, includedAreas:['Miami','Fort Lauderdale','Boca Raton','West Palm Beach'] },
  { id:'minneapolis-st-paul', name:'Minneapolis–St. Paul', metroTechRank:23, includedAreas:['Minneapolis','St. Paul','Bloomington'] },
  { id:'portland', name:'Portland Metro', metroTechRank:24 },
  { id:'detroit', name:'Detroit Metro', metroTechRank:25, includedAreas:['Detroit','Ann Arbor','Troy','Southfield'] },
  { id:'orlando', name:'Orlando Metro', metroTechRank:26 },
  { id:'tampa', name:'Tampa Bay', metroTechRank:27, includedAreas:['Tampa','St. Petersburg','Clearwater'] },
  { id:'kansas-city', name:'Kansas City Metro', metroTechRank:28 },
  { id:'columbus', name:'Columbus Metro', metroTechRank:29 },
  { id:'st-louis', name:'St. Louis Metro', metroTechRank:30 },
  { id:'jacksonville', name:'Jacksonville Metro', metroTechRank:31 },
  { id:'san-antonio', name:'San Antonio Metro', metroTechRank:32 },
  { id:'sacramento', name:'Sacramento Metro', metroTechRank:33 },
  { id:'indianapolis', name:'Indianapolis Metro', metroTechRank:34 },
  { id:'huntsville', name:'Huntsville Metro', metroTechRank:35 },
  { id:'cincinnati', name:'Cincinnati Metro', metroTechRank:36 },
  { id:'cleveland', name:'Cleveland Metro', metroTechRank:37 },
  { id:'richmond', name:'Richmond Metro', metroTechRank:38 },
  { id:'hartford', name:'Hartford Metro', metroTechRank:39 },
  { id:'inland-empire', name:'Inland Empire', metroTechRank:40, includedAreas:['Riverside','San Bernardino','Ontario','Rancho Cucamonga'] },
  { id:'hampton-roads', name:'Hampton Roads / Virginia Beach–Norfolk', metroTechRank:41, includedAreas:['Norfolk','Virginia Beach','Newport News','Chesapeake'] },
  { id:'milwaukee', name:'Milwaukee Metro', metroTechRank:42 },
  { id:'colorado-springs', name:'Colorado Springs Metro', metroTechRank:43 },
  { id:'albany', name:'Albany–Schenectady–Troy', metroTechRank:44, includedAreas:['Albany','Schenectady','Troy'] },
  { id:'omaha', name:'Omaha Metro', metroTechRank:45 },
  { id:'providence', name:'Providence Metro', metroTechRank:46 },
  { id:'boise', name:'Boise Metro', metroTechRank:47 },
  { id:'dayton', name:'Dayton Metro', metroTechRank:48 },
  { id:'rochester', name:'Rochester Metro', metroTechRank:49 },
  { id:'des-moines', name:'Des Moines Metro', metroTechRank:50 },
  { id:'las-vegas', name:'Las Vegas Metro', metroTechRank:51 },
  { id:'honolulu', name:'Urban Honolulu / Oʻahu', metroTechRank:52, includedAreas:['Honolulu','Oʻahu'] }
];

const techCities = [
  { id:'new-york-city', name:'New York City', cityTechRank:1, metroId:'nyc' },
  { id:'san-francisco', name:'San Francisco', cityTechRank:2, metroId:'san-francisco' },
  { id:'san-jose', name:'San Jose', cityTechRank:3, metroId:'san-jose' },
  { id:'seattle', name:'Seattle', cityTechRank:4, metroId:'seattle' },
  { id:'austin', name:'Austin', cityTechRank:5, metroId:'austin' },
  { id:'boston', name:'Boston', cityTechRank:6, metroId:'boston' },
  { id:'los-angeles', name:'Los Angeles', cityTechRank:7, metroId:'los-angeles' },
  { id:'chicago', name:'Chicago', cityTechRank:8, metroId:'chicago' },
  { id:'washington-dc', name:'Washington, DC', cityTechRank:9, metroId:'dc-nova' },
  { id:'dallas', name:'Dallas', cityTechRank:10, metroId:'dallas-fort-worth' },
  { id:'philadelphia', name:'Philadelphia', cityTechRank:11, metroId:'philadelphia' },
  { id:'san-diego', name:'San Diego', cityTechRank:12, metroId:'san-diego' },
  { id:'denver', name:'Denver', cityTechRank:13, metroId:'denver-boulder' },
  { id:'raleigh', name:'Raleigh', cityTechRank:14, metroId:'raleigh-durham' },
  { id:'phoenix', name:'Phoenix', cityTechRank:15, metroId:'phoenix' },
  { id:'charlotte', name:'Charlotte', cityTechRank:16, metroId:'charlotte' },
  { id:'salt-lake-city', name:'Salt Lake City', cityTechRank:17, metroId:'salt-lake-city' },
  { id:'nashville', name:'Nashville', cityTechRank:18, metroId:'nashville' },
  { id:'miami', name:'Miami', cityTechRank:19, metroId:'south-florida' },
  { id:'pittsburgh', name:'Pittsburgh', cityTechRank:20, metroId:'pittsburgh' },
  { id:'minneapolis', name:'Minneapolis', cityTechRank:21, metroId:'minneapolis-st-paul' },
  { id:'portland', name:'Portland', cityTechRank:22, metroId:'portland' },
  { id:'baltimore', name:'Baltimore', cityTechRank:23, metroId:'baltimore' },
  { id:'detroit', name:'Detroit', cityTechRank:24, metroId:'detroit' },
  { id:'orlando', name:'Orlando', cityTechRank:25, metroId:'orlando' },
  { id:'tampa', name:'Tampa', cityTechRank:26, metroId:'tampa' },
  { id:'kansas-city', name:'Kansas City', cityTechRank:27, metroId:'kansas-city' },
  { id:'columbus', name:'Columbus', cityTechRank:28, metroId:'columbus' },
  { id:'st-louis', name:'St. Louis', cityTechRank:29, metroId:'st-louis' },
  { id:'jacksonville', name:'Jacksonville', cityTechRank:30, metroId:'jacksonville' },
  { id:'san-antonio', name:'San Antonio', cityTechRank:31, metroId:'san-antonio' },
  { id:'sacramento', name:'Sacramento', cityTechRank:32, metroId:'sacramento' },
  { id:'indianapolis', name:'Indianapolis', cityTechRank:33, metroId:'indianapolis' },
  { id:'huntsville', name:'Huntsville', cityTechRank:34, metroId:'huntsville' },
  { id:'cincinnati', name:'Cincinnati', cityTechRank:35, metroId:'cincinnati' },
  { id:'cleveland', name:'Cleveland', cityTechRank:36, metroId:'cleveland' },
  { id:'richmond', name:'Richmond', cityTechRank:37, metroId:'richmond' },
  { id:'hartford', name:'Hartford', cityTechRank:38, metroId:'hartford' },
  { id:'riverside', name:'Riverside', cityTechRank:39, metroId:'inland-empire' },
  { id:'norfolk', name:'Norfolk', cityTechRank:40, metroId:'hampton-roads' },
  { id:'milwaukee', name:'Milwaukee', cityTechRank:41, metroId:'milwaukee' },
  { id:'colorado-springs', name:'Colorado Springs', cityTechRank:42, metroId:'colorado-springs' },
  { id:'albany', name:'Albany', cityTechRank:43, metroId:'albany' },
  { id:'omaha', name:'Omaha', cityTechRank:44, metroId:'omaha' },
  { id:'providence', name:'Providence', cityTechRank:45, metroId:'providence' },
  { id:'boise', name:'Boise', cityTechRank:46, metroId:'boise' },
  { id:'dayton', name:'Dayton', cityTechRank:47, metroId:'dayton' },
  { id:'rochester', name:'Rochester', cityTechRank:48, metroId:'rochester' },
  { id:'des-moines', name:'Des Moines', cityTechRank:49, metroId:'des-moines' },
  { id:'las-vegas', name:'Las Vegas', cityTechRank:50, metroId:'las-vegas' },
  { id:'honolulu', name:'Honolulu', cityTechRank:51, metroId:'honolulu' }
];

function getTechMetroForLocation(location) {
  const cityName = String(location).trim().toLowerCase();
  const majorCity = techCities.find(city => city.name.toLowerCase() === cityName ||
    (TECH_CITY_APPLICATION_ALIASES[city.name] || []).some(alias => alias.toLowerCase() === cityName));
  if (majorCity) return techMetros.find(metro => metro.id === majorCity.metroId) || null;
  return techMetros.find(metro => (metro.includedAreas || []).some(area => area.toLowerCase() === cityName)) || null;
}
